version: 2
jobs:
  android:
    # working_directory: ~/react-native-acpanalytics/android
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout:

      - run:
          name: Building Android Project
          command: make build-android

  ios:
    macos:
      xcode: "10.0"

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:

      - run:
          name: Building iOS Project
          command: make build-ios

workflows:
  version: 2
  android-ios:
    jobs:
      - android
      - ios
