require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'



target 'ACPAnalyticsSample_tvOS-tvOS' do

  platform :tvos, '12.0'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # use_flipper_tvos!

  target 'ACPAnalyticsSample_tvOS-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end

post_install do |installer|
  flipper_post_install(installer)
end
